### ISSUE TITLE
Unable to get class definition

### ISSUE THREAD

**Issue by nnWhisperer** [gccxml/pygccxml#110]
Hi, I have skimmed through the API for 5 hours and experimented with different functions, however, am not able to find a related place. Using the cpp file, I am running
```
for decl in global_namespace.declarations:
    print(decl, decl.location.file_name, decl.location.line)
```
and I can only get header files and declaration line numbers in the header file. I give cpp input and I need the positions of the class implementations, for example the non-artificial constructors I'd defined. However, I have not been able to find it in the API, this seems to be a very basic feature. Where could I look at @iMichka ? Thank you,

**Comment by iMichka** [comment]
Hi.

If I remember well, you can only get information about your header files.

Basically, pyggcxml reads the xml file produced by castxml. If the information you need is in the xml file but missing in pygccxml, we can have a look. I would run castxml on your files, and look at the output first. The xml content is quite easy to understand.

**Comment by nnWhisperer** [comment]
I've double-checked that, yes indeed although the input to the castxml is cpp, it only traces header files as the xml output shows. Thank you.
