### ISSUE TITLE
Issue about getting gccxml to work

### ISSUE THREAD

**Issue by zurach** [gccxml/pygccxml#20]
I've compiled gccxml using VC++ 10 version on Windows 8. I have both pygccxml and gccxml latest versions installed on my system. There is no problem when using gccxml standalone from commandline but if I try to run it through pygccxml API, I always get the error: "gccxml_runtime_error_t: Error occured while running GCC-XML."

I am not able to resolve this problem by myself.
Helps would be really appreciated.

**Comment by iMichka** [comment]
Hi

first, thank you for reporting. In fact it is more a gccxml problem than pygccxml problem. You need to use vc++09 on windows to make it work.

The author of gccxml, Brad King, has made a new tool, called castxml, which is working with Clang and never windows compilers. I am currently working on it's integration in pygccxml. We will make an announcement once it is ready.

**Comment by zurach** [comment]
What about using VC++ 08 instead of 09, would it matter?

**Comment by iMichka** [comment]
Should be no problem. Versions under 09 are OK.

**Comment by iMichka** [comment]
Hi

pygccxml 1.7.0 is now out, with support for CastXML, which replaces GCCXML. CastXML works with newer compilers so you can now migrate to a newer version of VC++.

You can find the changelog and some explanations here: http://pygccxml.readthedocs.org/en/develop/history.html

Sorry for the delay, it took longer than expected.

I'll close this bug, please reopen a new one if you have any trouble with CastXML or the new version of pygccxml.
