### ISSUE TITLE
commit: 5dfded3 "More pep8 fixes"  broke 'utils.py'

### ISSUE THREAD

**Issue by carsten-forty2** [gccxml/pygccxml#21]
Hello,
I dont't understand completely why, but the function:

def contains_parent_dir(fpath, dirs)

from pygccxml/utils/utils.py

raise the following exception after the mentioned commit.

INFO GCCXML version - 0.9( 1.135 )
Traceback (most recent call last):
  File "/home/carsten/src/bert/trunk/python/generate_pybert_code.py", line 297, in <module>
    generate(defined_symbols, options.extraIncludes, options.gimliBuild)
  File "/home/carsten/src/bert/trunk/python/generate_pybert_code.py", line 181, in generate
    , indexing_suite_version = 2)
  File "/home/carsten/src/gimli/thirdParty/dist-GNU-4.8.3-64/pyplusplus/module_builder/boost_python_builder.py", line 95, in __init__
    , indexing_suite_version)
  File "/home/carsten/src/gimli/thirdParty/dist-GNU-4.8.3-64/pyplusplus/module_builder/boost_python_builder.py", line 153, in __parse_declarations
    self.__apply_decls_defaults(decls)
  File "/home/carsten/src/gimli/thirdParty/dist-GNU-4.8.3-64/pyplusplus/module_builder/boost_python_builder.py", line 177, in __apply_decls_defaults
    self.__filter_by_location( flatten_decls )
  File "/home/carsten/src/gimli/thirdParty/dist-GNU-4.8.3-64/pyplusplus/module_builder/boost_python_builder.py", line 163, in __filter_by_location
    if pygccxml_utils.contains_parent_dir( fpath, self.__parsed_dirs ):
  File "/home/carsten/src/gimli/thirdParty/dist-GNU-4.8.3-64/pygccxml/utils/utils.py", line 118, in contains_parent_dir
    return bool(list(filter(fpath.startswith(dirs), dirs)))
TypeError: startswith first arg must be str, unicode, or tuple, not list

With the old version everything works perfectly.

There seems to be some more problems folllowing up and broke my toolchain with the current branch .. i will investigate and send it.

Bests and thanks for maintaining this great software,
Carsten

**Comment by iMichka** [comment]
Hi. Thanks for reporting.

I'll have a look this week. This method is not checked by any test, so that's why I did not see any error while running the test suite. I'll see if I can write a test and fix the problem.

**Comment by iMichka** [comment]
Hi again. I fixed the contains_parent_dir function in 24c2544378533de1d23a8011fffa8e71d0c9d750 .
I also added a test so that it won't break in the future.

Just a question, why are you needing this function ? It was previously used internally by pygccxml, but as of today it is not used anywhere. I am asking this because I don't know if I want to keep this function around or deprecate it (less code to maintain on my side). It depends of course on the functions utility and usage.

**Comment by carsten-forty2** [comment]
Quoting Michka Popoff <notifications@github.com>:

> Hi again. I fixed the contains_parent_dir function in  
> 24c2544378533de1d23a8011fffa8e71d0c9d750 .
> I also added a test so that it won't break in the future.
>
> Just a question, why are you needing this function ? It was  
> previously used internally by pygccxml, but as of today it is not  
> used anywhere. I am asking this because I don't know if I want to  
> keep this function around or deprecate it (less code to maintain on  
> my side). It depends of course on the functions utility and usage.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gccxml/pygccxml/issues/21#issuecomment-78157919

Hi again ..

I'm running pyplusplus for the automatic generation of the python  
bindungs for my c++ project.
Pyplusplus is calling this method .. and a lot more I guess. I hope  
removing spurious unused stuff will not break pyplusplus.
But of course I can help testing. Beside mine .. I know another big  
project using both pygccxml and pyplusplus.

Bests,
Carsten

**Comment by iMichka** [comment]
Okay at least I know I need to be careful when removing stuff, especially for pyplusplus. I'll leave the function in there then. Thanks.
