### ISSUE TITLE
Python bindings and pygccxml missing in Centos 6.4

### ISSUE THREAD

**Issue by engmas5** [gccxml/pygccxml#23]
I trying to install ns3 on centos 6.4 since I have to work with a specific os and kernel versions for atheros wlan device feauture I need. I followed the instructions to install all pre-requisite for ns3 and proceeded to ns3 installation and it seems fine. Also I installed Python binding. However, I couldn't run .py tests and codes. When I run ./waf --apiscan=all I received that "(py)gccxml" is missing and rescan APIs message.  Also I received "python bindgen missing" when I run ./waf configure.
I installed pygccxml successfully from source and could locate it using "locate" and "find" commands. 
Am I missing something that could help the system to see the bindings. I hope you have a solution for this problem.

**Comment by iMichka** [comment]
Hi

how did you install pygccxml ?
The preferred way is to use:
```pip install pygccxml```

Then you should be able to use: "import pygccxml" in python, wherever you are. If not, there is a problem with the installation or your pip setup.

**Comment by engmas5** [comment]
Hi IMicka, Thank you for your quick reply.
I already installed pygccxml using pip command and noticed the problem and then I installed it from source code using
>>  python setup.py install 

it seems that python can see pygccxml. I could import it in python shell:
>> import pygccxml


In addition, I installed gccxml from .rpm binaries.  The problem stay the same: python test.py skipped .py files and I couldn't run my .py script. After ./waf configure

>> Python module pybindgen                                                                          : not found              
>> pybindgen missing => no python bindings               

and after ./waf --apiscan=all

>> Waf: Entering directory `/home/dsa/ns-3-allinone/bake/source/ns-3-dev/build'
>> Cannot re-scan python bindings: (py)gccxml not available

You mentioned that it could be pip problem, could you elaborate more.

**Comment by engmas5** [comment]
Hi iMicka, 
I think I figured out the problem. pygccxml needs python2.7 to build.  In centos 6.4 , python2.6.6 is installed by default. this causes the python binding for ./waf configure to miss the python bindings.
Note that you need gccxml installed
to solve the problem:
> 1) I installed python 2.7.9
> 2) Changed python version in the system to python2.7 
> 3) Rebuilt pygccxml from source code using (python setup.py install) command.
> 4) Checked valid installation of pygccxml using python command line:

>> import pygccxml

> 5) Reconfigured ./waf using ./waf configure
> 6) built ns-3 using ./waf build

The main step that points out the problem is that I tried to install pygccml from .rpm package and the command line showed that this library needs python2.7, then I followed the steps above and it work fine. It can run examples and my python scripts too. 

Thank you iMicka for your interest and help.

**Comment by iMichka** [comment]
Hi

it's great you found the solution. I guess the .rpm package on cent os installs an old version of pygccxml. Normally, since I overtook the project (version 1.5.2), pygccxml should work with python 2.6, 2.7, 3.2, 3.3, and 3.4. Maybe there were problems with this old version or some misconfiguration in the python path if you have multiple python installed. Anyway; I'll close this ticket as it works for you.
