### ISSUE TITLE
Add CastXML Travis build

### ISSUE THREAD

**Issue by iMichka** [gccxml/pygccxml#37]
To prepare for the migration to CastXML as being the default xml parser, we need a Travis build running CastXML.

Once solution would be to installed castxml like I did with gccxml, but the debian package is currently only available in Ubuntu Wily.

Castxml is now available in homebrew, so that seems to be fastest solution. The https://github.com/gccxml/pygccxml/tree/TravisCastXML branch is already up and running; but castxml currently crashes. Once this is cleared we should have a build to start with.

I could also download and use the precompiled castxml we are using in ITK (either on Mac or Linux). Let's see what works out best.

**Comment by mamoll** [comment]
I download the binaries from Kitware in the .travis.yml for ompl: https://github.com/ompl/ompl/blob/master/.travis.yml
That seems to work.

**Comment by iMichka** [comment]
Hey, super cool.

I think I will use that until I get the homebrew package to work on Travis. Thanks for the hint.
