### ISSUE TITLE
download_url in setup.py should point to github tag snapshot instead

### ISSUE THREAD

**Issue by Arthur2e5** [gccxml/pygccxml#48]
The current `download_url` is hardcoded to https://github.com/gccxml/pygccxml/archive/master.zip, and it causes confusion in the PyPI page for older versions. It's better to make use of GitHub tag snapshots like:
````Py
version="v1.7.3"
setup(...,
      version=version,
      download_url="https://github.com/gccxml/pygccxml/archive/{0}.tar.gz".format(version),
      ...)
```

You can also use ZIPs like what you have done currently, but ZIPs almost mean losing a couple of attributes. (I don't know if GitHub uses Info-ZIP extensions -- if they do so, then there's no such problem. But tar-gz archives provide solid, whole-archive compression.)

**Comment by iMichka** [comment]
Thanks for notifying me. +1 on using tar.gz.

I update the url, so this makes clear which file should be downloaded for which release; though looking at different setup.py files, people have written different things for this keyword, even just a link to a html page containing the actual links and some text. So this URL is actually not used by the download mechanism. What you are downloading are wheels.

What happened is that pyggcxml had a non-conventional versioning scheme, at least for PyPI. The ```v``` in front is not recognised by pip. I tried to outsmart PyPI, but it breaks the upload/distribution at different levels. Release 1.7.0 was for example deleted from PyPI and re-uploaded, which resulted in a big mess. So trying to download an older version (before 1.7.3) is just broken. Actually I found PyPI relatively broken regarding package uploading: it allows you to hack things around in the admin panel, but once you do so you basically break a lot of things.

I have no preference for the v, it is there only for historical reasons, but this was probably an error.

For release 1.7.4, I will drop the ```v```. It should hopefully not confuse anybody, and I'll add a note in the changelog. I hope this will stabilise PyPI releases for the future.

**Comment by Arthur2e5** [comment]
It looks like the github 1.7.4 tags have a `v` prefix (which is a normal practice) while the tarball link in setup.py doesn't. The correct URL should be https://github.com/gccxml/pygccxml/archive/v1.7.4.tar.gz...

**Comment by Arthur2e5** [comment]
(Looks like I can't reopen this.)

**Comment by iMichka** [comment]
You cant't re-open because I closed this bug, and this is how github handles it. I should have let you close the bug yourself for it to work.

The ```v``` in the tag is my fault. I thought I had done it right, and did not realise I had made an error when pushing the branch. It's probably because I used gitflow, and the tag name was generated from the branch name, which I had set as v1.7.4 before. What is done is done. There is now a 1.7.5 branch, which I just created. I hope I'll get the tagging right next time. Thanks for letting me know.

**Comment by Arthur2e5** [comment]
Actually GitHub recommends a `v`-prefixed tagname for their 'releases' page (i.e. annotated tags) too. I guess they are doing that to avoid ambiguities when doing `checkout`.

**Comment by iMichka** [comment]
Okay I re-created the 1.7.5 branch. I found some interesting discussions about the v prefix in the meantime. I decided that I'll keep the v (git tags) for github, and no v for the pip versions. This should make everybody happy. See https://github.com/gccxml/pygccxml/commit/b990e0cf7b2588637832ef000d88014fcae5daa9
