### ISSUE TITLE
RTFD badge broken by 0974027

### ISSUE THREAD

**Issue by Arthur2e5** [gccxml/pygccxml#50]
New `readthedocs.io` URLs were used in 0974027. The new url seem to give a `text/html` (https://readthedocs.org/?version=master, actually) in its final destination and fails the image. Likewise, the https://readthedocs.io/projects/pygccxml/?badge=master link only takes you to https://readthedocs.org/?badge=master. Since the badges are not part of the pygccxml project-subdomain, it's almost certain that it's a mistake to change the badge URLs too.

Regarding project-subdomains, personally I don't think it's a good idea to change as long as https://readthedocs.org/projects/pygccxml/ is giving the `.org` site instead of the `.io` site...

**Comment by iMichka** [comment]
Should be good now. I was too hasty at changing all the urls ...

**Comment by iMichka** [comment]
I just released version 1.7.5. Everything should hopefully be fine now. I'll let you close this bug.
