### ISSUE TITLE
Use a Unicode arrow (→) in docs/upgrade_issues.rst

### ISSUE THREAD

**Issue by Arthur2e5** [gccxml/pygccxml#51]
The current `->` arrow doesn't look good in browsers or in RTFD PDFs. Consider using an arrow character.

**Comment by Arthur2e5** [comment]
It seems that the examples under "Free and member function default arguments" are not well separated either. Consider writing a few words in these `*` lists...

**Comment by iMichka** [comment]
Hi. Thanks for notifying me. I made some small changes to this page.
This is some legacy documentation which was written before I overtook the project.

I will probably not invest much time to improve that page, as it will be phased out in one of the next releases. A general documentation overhaul is planned, I am working slowly on it.

Feel free to open pull requests if you see small errors/typos, I'll happily merge them.

Is that part of the update for gccxml of interest for you, or did you just stumble over this page while reading the manual ? Also, if you have an interesting project using pygccxml, let me know, I am trying to make a list of projects that are using this library.
