### ISSUE TITLE
Wrong decl_type for function pointers ?

### ISSUE THREAD

**Issue by teto** [gccxml/pygccxml#61]
When the argument is a function pointer, there seems to be a few problems:

For instance for the function `int atexit(void (*function)(void));`, the pygccxml code `decl.arguments[0].decl_type` returns: `void (*)( ) *` which has 1 more asterisk then necessary ?

Nb: I made a mistake and ended up posting it first here
https://github.com/CastXML/CastXML/issues/67

**Comment by iMichka** [comment]
Thanks for reporting.

I will be on holidays for 3 weeks, so I will only able to have a look at this end of August. I will probably not have internet so I won't be able to respond to any questions/mails.

**Comment by teto** [comment]
No problem, I have a workaround :) 
Before you leave ( if you have the time, else no worry ) could you give me pointers (like what file to look into, what do you think is wrong) for https://github.com/gccxml/pygccxml/issues/62 which is the only blocking pb for me. I might be able to provide a fix.
Enjoy your holyday to the fullest.

**Comment by iMichka** [comment]
Hi

I had a look at this problem. I do not think that it is a bug at first.

If you print ```type(decl.arguments[0].decl_type)``` you will see that the type is of ```pointer_t```. Normally you would then use ```declarations.remove_pointer()``` to remove that type level and access the underlying ```free_function_type_t```. The ```declarations.remove_pointer()``` function was broken and I fixed that, make sure you use the latest checkout from the develop branch.

I wrote an example to explain how these nested types work:
http://pygccxml.readthedocs.io/en/develop/examples/nested-types/example.html

And a more specific example for function pointers, which is the case you are treating here:
http://pygccxml.readthedocs.io/en/develop/examples/function-pointer/example.html

Hope that helps. Please close this bug if this works for you.

**Comment by teto** [comment]
when I ask for "decl.arguments[0].decl_type", do you agree it should return  `void (*)( )` and not
`void (*)( ) *` ?  This is a function pointer, not a pointer to a function pointer, IMO I shouldn't have to call declarations.remove_pointer() .

**Comment by iMichka** [comment]
Yes I guess the * is not wanted in that case. I am not using C++ often, so function pointer / pointer things are sometimes a little bit hairy for me.

I made a small change to the develop branch. I special-cased the function pointer decl_type creation, and the * is now gone.

The type is still ```pointer_t```. One thing that may need to be done is to introduce a ```calldef_pointer_t``` class, extending ```pointer_t```. Not sure this is needed anyway. It would require some work, for something that can still be checked with the is_calldef_pointer function.

Please tell me if that change is OK for you. I will apply that specific patch to the next 1.8.1 release then.

**Comment by iMichka** [comment]
I'm closing this bug, as I consider the problem as fixed for now. Do not hesitate to open a new one if this does not work for you.

**Comment by teto** [comment]
The commit is in develop branch: is that the branch that will become pygccxml1.9 ? or should I cherry pick the commit ?
I am waiting for the struct fix in castxml before relaunching my tests.

**Comment by iMichka** [comment]
At the moment yes, but 1.9.0 will probably not go out before next year. It took at least 1 year between 1.7.0 and 1.8.0.

I will just make a 1.8.1 release with that specific fix, probably next week. I am currently looking at the struct thing.
