### ISSUE TITLE
pygccxml fails in enum/typedef hash function

### ISSUE THREAD

**Issue by dermont123** [gccxml/pygccxml#70]
`  File "./../pygccxml/declarations/enumeration.py", line 51, in __hash__
    return super(enumeration_t, self).__hash__(self)
TypeError: __hash__() takes exactly 1 argument (2 given)

    def __hash__(self):
        return super(enumeration_t, self).__hash__()
       -->  #return super(enumeration_t, self).__hash__(self)

    def __hash__(self):
        return super(typedef_t, self).__hash__()
        --> #return super(typedef_t, self).__hash__(self)
`
[hash.zip](https://github.com/gccxml/pygccxml/files/779513/hash.zip)

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.

I had already fixed this some time ago, but only on the `develop` branch (https://github.com/gccxml/pygccxml/commit/8db77ca1b9c0c9eb04d47dbca0f1caeb230c1b71). I saw this when running pygccxml with `pypy`.

I will backport the patch and create a 1.8.5 release this weekend.

**Comment by iMichka** [comment]
I created the `1.8.5` release branch that can be used for testing purposes:
https://github.com/gccxml/pygccxml/tree/hotfix/v1.8.5

I am waiting on another patch to be tested first, and as soon as this is done, I'll make the release. It may take 1 or 2 days before I have time to make the release though.

**Comment by dermont123** [comment]
Ok I'll try it out, but the changes for the typdef/enum were ones I already tested so I know it already resolves the problem.
return super(enumeration_t, self).__hash__()
return super(typedef_t, self).__hash__()

The above don't appear to be on the devlop branch.

**Comment by iMichka** [comment]
Yes, it will once the 1.8.5 branch is merged to develop too.

**Comment by iMichka** [comment]
I just released 1.8.5, which was uploaded to pypi too. The changes are in the develop branch too. Closing here. Thanks for reporting again, and for your patience.
