### ISSUE TITLE
Setup travis builds for castxml epic version 1

### ISSUE THREAD

**Issue by iMichka** [gccxml/pygccxml#74]
Due to the introduction of the new xml format version in castxml, which can be enabled by using the `--castxml-output=1` flag, the buildbots need to be upgraded.

For this we need:
- New castxml binaries for OS X, Linux and Windows.
- Make all the castxml tests run twice on travis and appveyor: once with and without the new flag. The builds will run twice as long, but this is still acceptable (around 5 to 6 min).

**Comment by iMichka** [comment]
@thewtex Would you have time to build new CastXML binaries? There is nothing urgent but ITK could also benefit from the upgrade. No real new features for ITK, but there were some small patches lately.

I was also thinking if we should use circle/travis to get the binaries built, but I guess you have some setup locally at Kitware for building this.

**Comment by thewtex** [comment]
@iMichka CastXML builds are currently configured here:

  https://github.com/thewtex/CastXMLSuperbuild

It would be nice to move this to the `CastXML` or `gccxml` GitHub organizations. It currently has a Linux build on CircleCI, and I just grab the artifact and upload it. It would be nice to have Travis and Appveyor although the LLVM build time might be a challenge -- I have not tried.

It will be at least a couple of weeks before I can get to the updates.

**Comment by iMichka** [comment]
Thanks Matt. No rush. I have a local build, so I can continue playing around the time being. Adding the new feature will take some time anyway.

I am +1 on moving this project. It would better fit under the CastXML organisation.

For travis, we could use their mac builds, and the llvm bottled by homebrew. That should be quite easy to do and no llvm will need to be done.

For the windows build, it may be more tricky.

**Comment by iMichka** [comment]
Closing here. Tests are running with both the old and new castxml versions.

@thewtex Thanks for building new releases and adding them to ITK too. I was able to build the linux binaries using your docker (before you built them for ITK), it worked pretty well.

**Comment by thewtex** [comment]
:+1:
