### ISSUE TITLE
Creating reference (or reference-to-const) from a class_t

### ISSUE THREAD

**Issue by ombre5733** [gccxml/pygccxml#75]
I'm not sure how to accomplish the following: I have a `class_t` and would like to create a reference to this class. Finally I would like to get the full name. For example, my global namespace has an `Object` and I would like to create a `Object&` or even `const Object&`.

Here is what I have tried:

    >>> c = globalNamespace.class_("Object")
    >>> c
    <pygccxml.declarations.class_declaration.class_t object at 0x7f7ecd655850>
    >>> print(c)
    Object [class]
    >>> r = reference_t(c)
    >>> print(r)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/cpptypes.py", line 24, in __str__
        res = self.decl_string
      File "/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/cpptypes.py", line 51, in decl_string
        self.cache.decl_string = self.build_decl_string()
      File "/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/cpptypes.py", line 596, in build_decl_string
        return self.base.build_decl_string(with_defaults) + ' &'
    AttributeError: 'class_t' object has no attribute 'build_decl_string'

**Comment by iMichka** [comment]
Hi.

You need to pass an object which has a `build_decl_string` method. That would be any class from the `type_t` hierarchy. As you are working on a class, you will need to use the intermediary class `declarated_t`.

So first create a `declarated_t` object, using `c` as parameter in the constructor. Use this new object as argument for the creation of a `reference_t`.

Hope that helps.

**Comment by ombre5733** [comment]
@iMichka Thanks that is what I wanted!
