### ISSUE TITLE
Running the Unit Tests

### ISSUE THREAD

**Issue by dermont123** [gccxml/pygccxml#78]
Trying to tun the unit tests from the pygccxm source unitests dir, used to  able to do so, now with python2/python3.

python decl_string_tester.py
Traceback (most recent call last):
  File "decl_string_tester.py", line 9, in <module>
    from . import autoconfig
ValueError: Attempted relative import in non-package

**Comment by iMichka** [comment]
Hi. Yes, I changed that lately. You can use `python3 -m unittests.decl_string_tester`.

I documented this in the readme too: cbba23503c37e204266daf1e2c91eab91fb61a27

**Comment by dermont123** [comment]
Sorry I missed (i.e. didn't read) the updated readme.

**Comment by iMichka** [comment]
I updated the readme after you opened this bug, so no blame here. Feel free to ask questions, feedback is always welcome.
