### ISSUE TITLE
Problem after const qualifiers moved

### ISSUE THREAD

**Issue by dermont123** [gccxml/pygccxml#79]
I'm not sure why the const qualifiers has been moved to the left side of the declaration string.

https://github.com/gccxml/pygccxml/commit/16c536031407f25ee0b712177197025c31e94269#diff-6ae1b6ab39da4a9fe909fc7298a821b7

This is a pain and requires so many changes/testing etc. that I reverted back to an older version.

For example the following produces code that doesn't compile.
`
struct Object{};
// can't change data or pointer
void genVertices(const int* const offsets);
void genObject(const Object* const offsets);

f = self.global_ns.free_fun('genObject')
print (f.arguments[0].decl_type.decl_string)  ## const const int *

f = self.global_ns.free_fun('genObject')
print (f.arguments[0].decl_type.decl_string)  ## const const ::Object *
`

**Comment by iMichka** [comment]
Hi. Thanks for reporting.

I did that change a few days ago. I knew that it would maybe break people's code. If that is the case, I will add an option flag to enable the old/new behaviour.

Though the new output looks wrong too, I did not think about testing your use case.
I will add this code to the test suite, so we will have some more testing around these cases.

I will try to investigate this as soon as possible. Rest assured that this change will not be in the final 1.9.0 release if it breaks people's code. It's good that you tested the develop branch, there are a lot of tests but even with this, things get's sometimes broken.

**Comment by praetorian20** [comment]
@iMichka The new output is wrong syntax, you can't have multiple `const` qualifiers like that. It can be one of
- `const int * const`
- `int const * const`

The same applies to `volatile` and `const volatile` too, so maybe you could add test cases for all 3?

**Comment by iMichka** [comment]
Yes I will add test cases for all the combinations. I do not think the change is completely wrong, at least inverting the order it were I did it makes more sense IMHO. I need to have a close look at the order of the chaining of the different declarations for these situations.

**Comment by iMichka** [comment]
Ok I reverted that change, and added some more tests.

It's now clearer to me what is going on here.
As for example `int const` == `const int`, I wanted to have the const on the left as default.

But this is not always valid, especially in the case described here. And I do not want to mix the conventions. I re-read some c++ doc, and in fact, having the const on the right hand side will always work, as it is preferred to read from the right to the left. I will write this down somewhere in the FAQ or in an example.

Please test. This should be fixed now.

**Comment by dermont123** [comment]
Thanks, fixed now.

**Comment by iMichka** [comment]
Great. Closing here. I will add some examples/documentation/explanations about the order later.
