### ISSUE TITLE
Drop support for Python 2.6 and Python 3.2

### ISSUE THREAD

**Issue by iMichka** [gccxml/pygccxml#80]
Basically this is only removing the Python 2.6 and Python 3.2 builds from travis.
When code pops up that can be modernised, it can then be done as necessary.

Python 2.6 is pretty old now. Systems with Python 2.6 are probably stuck with gccxml, or need to go through some more work to get castxml compiled there with a new llvm version. So those can pin the pygccxml version to 1.9.x in their package manager.
Anyway this version has been EOL since 2013. https://www.python.org/dev/peps/pep-0361/

Python 3.2 is EOL since february 2016, so it can be dropped. With this I will be able to remove the workarounds in the travis file which were already a pain to implement. https://www.python.org/dev/peps/pep-0392/

**Comment by RomanYakovenko** [comment]
Will you drop support for python 2.*?

**Comment by iMichka** [comment]
For release 1.2.0, I am removing Python 2.6 and Python 3.2
I will still support 2.7, 3.3, 3.4, 3.5, 3.6, pypy2 and pypy3 with 1.2.0

When I tell removing support; I just mean removing the travis tests. There is not so much python 2.6 or 3.2 specific code in pygccxml. So 1.2.0 may even work with 2.6, but I am not guaranteeing it.

For people who want to use deprecated Pythons they can:
- use pygccxml 1.9.x
- copy pygccxml in their project, and patch with whatever fixes they need

**Comment by hugovk** [comment]
Python 2.6 and 3.2 have been removed from Travis CI in https://github.com/gccxml/pygccxml/commit/b2135b92d22d60a5a73139caf9564ad1c2917bb0#diff-354f30a63fb0907d4ad57269548329e3.

Can this issue be closed?

By the way, here's the pip installs for pygccxml from PyPI for the last year:
```
$ pypinfo -d 365 --percent --pip pygccxml pyversion
python_version percent download_count
-------------- ------- --------------
2.7              65.4%          4,778
2.6              25.6%          1,866
3.6               4.0%            289
3.5               3.3%            238
3.4               1.8%            128
3.3               0.0%              3

```

You could consider dropping Python 3.3 as well, it went EOL last month and has very low numbers.

**Comment by iMichka** [comment]
I. Thanks for letting me know. I was hoping to cut the 2.0 release earlier, so I was thinking to leave 3.3 in there. But as it is now EOL and has 3 downloads in the last 365 days, I removed it too from the travis build with 1ed25bda6a25f7f1bd4efdf9e6ed64c43afe592f.

Let's close this issue then. Older code can now be updated to newer python syntax :)
