### ISSUE TITLE
xml_generator_configuration_t.xml_generator_path default value

### ISSUE THREAD

**Issue by RomanYakovenko** [gccxml/pygccxml#83]
Hello. A small request for improvement.
Starting with Python 3.3 (https://docs.python.org/3/library/shutil.html) shutil package contains "which" function. From the doc: "... Return the path to an executable which would be run if the given cmd was called ..."
Since version 2.0 deprecates gccxml, pygccxml will have only 1 xml generator. If  "xml_generator_path" was not passed in __init__, the package can try to resolve castxml executable location via shutil.which functionality. 

Thank you
P.S. I am still learning git, so no pull request at this time, sorry.

**Comment by iMichka** [comment]
Thanks, I didn't know about this new function. As I want to still keep python 2.7 around, I will not be able to use this directly. But I think I will wrap this with a python 2.7/3.3 check, as this is an way more elegant way to fetch castxml's path.

**Comment by iMichka** [comment]
That's now implemented in the `develop` branch with e2e213257557e54ecf10e78b0310909df84de6d6. Thanks for the hint.
