### ISSUE TITLE
find_noncopyable_vars bug

### ISSUE THREAD

**Issue by RomanYakovenko** [gccxml/pygccxml#84]
Hello. Consider the following code:
struct abstract{
    virtual void do_smth() = 0;
};

struct holder{
    abstract* ptr;
};

find_noncopyable_vars(holder) will return "ptr" member variable as noncopyable variable, which of course wrong.

[patch.txt](https://github.com/gccxml/pygccxml/files/1156823/patch.txt)

Attached is a patch, which fixes exactly this situation.
I run the tests and all tests passed (Ubuntu 16.04, Python3.5) 
 
Regards,
Roman

**Comment by iMichka** [comment]
Hi Roman. Thanks for the patch. I am currently on holidays and I will come back next week. I'll have a look at this when I am back. And at all the other issues/comments you made.

**Comment by RomanYakovenko** [comment]
On Sat, Jul 29, 2017 at 4:30 PM, Michka Popoff <notifications@github.com>
wrote:

> Hi Roman. Thanks for the patch. I am currently on holidays and I will come
> back next week. I'll have a look at this when I am back. And at all the
> other issues/comments you made.
>

Enjoy your vacation. I also was on vacation: Oberkirch & Baden-Baden.
Regards,
Roman

**Comment by iMichka** [comment]
Should be fixed now with 4a40a9bb1ed61505fd622954eb918dda2245191f. Please test.

**Comment by iMichka** [comment]
I made the change on the `develop` branch. Once you tested, I'll backport it to master, and I'll make a 1.9.1 release, because 2.0.0 will take a little bit more time to be done.

**Comment by RomanYakovenko** [comment]
Thank you
