### ISSUE TITLE
"Remove useless super delegation" commit breaks existing code 

### ISSUE THREAD

**Issue by RomanYakovenko** [gccxml/pygccxml#88]
The commit removes "__hash__" method. 
According to the documentation (https://docs.python.org/3/reference/datamodel.html#object.__hash__) 

...
A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking isinstance(obj, collections.Hashable).
...

The pygccxml.declarations classes defines __eq__ method, so the __hash__ method should be defined too. 

Thanks

**Comment by iMichka** [comment]
Hi. Thank you for letting me know. This is not caught by the tests, so for me this was fine. Also, it is weird, as this is just a delegation to super, as the parent class still has a defined hash method. I will need to investigate this more.

Any c++ code and practical pygccxml example which shows when/why this is needed?

**Comment by RomanYakovenko** [comment]
Plenty.

struct A{};
typedef A AA;
typedef A AAA;
void f1(AA);
void f2(AAA);

Now, consider a pygccxml user, which has to do something once with the function arguments; 

__hash__ helps to implement the logic efficiently. py++ uses this functionality all over the code.

**Comment by iMichka** [comment]
Yes, this makes sense. It is part of the public API of pygccxml and needs to be working. I used a slightly different syntax, and fixed it. I also added some tests that make sure the __hash__ methods does not return None, so this is documented. Thanks for the hint.
